textModels:
  enabledOrder:
    - '111'
  items:
    - alias: '111'
      strategy: openai-compatible-text
      enabled: true
      credentials:
        apiKey: ark-bab9dd9c-8576-460e-9c65-eb309afdf1cd-ff4fe
        endpoint: https://ark.cn-beijing.volces.com/api/plan/v3
      params:
        vendor: volcengine_agent_plan
        model: glm-5.1
imageModels:
  enabledOrder:
    - 图像模型1
  items:
    - alias: 图像模型1
      strategy: openai-compatible-image
      enabled: true
      credentials:
        apiKey: ark-bab9dd9c-8576-460e-9c65-eb309afdf1cd-ff4fe
        endpoint: https://ark.cn-beijing.volces.com/api/plan/v3
      params:
        vendor: volcengine_agent_plan
        model: doubao-seedream-5.0-lite
